name: PHP Composer

on:
  push:
    branches: [ master, 'up' ]
  pull_request:
    branches: [ master, 'up' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: nanasess/setup-php@master
        with:
          php-version: '8.1'

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-$GITHUB_REF-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: cd app && composer install --prefer-dist --no-progress --no-suggest && composer dump-autoload -o

      - name: Update README
        env:
          README_LOGIN: ${{ secrets.README_LOGIN }}
          README_TOKEN: ${{ secrets.README_TOKEN }}
        run: php app/bin/console.php artarts36:readme:update
